services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf   
    depends_on:
      - app
    networks:
      - todolist 

  db:
    image: postgres:latest
    volumes: 
      - ./instance:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_DB}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"] # Verifica se o PostgreSQL está pronto
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - todolist

  app:
    build:
      context: .
      dockerfile: Dockerfile
    
    volumes:
      - ./instance:/app/instance

    environment:
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_DB=${DATABASE_DB}
      - DATABASE_HOST=${DATABASE_HOST}
    
    depends_on:
      db:
        condition: service_healthy
    networks:
      - todolist

networks:
  todolist:

