services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - todolist
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./instance:/app/instance

    environment:
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_DB=${DATABASE_DB}
      - DATABASE_HOST=${DATABASE_HOST}
    networks:
      - todolist

networks:
  todolist: